# Generated by Django 5.0.7 on 2024-08-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
    ]
